apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-customer-management-deployment
spec:
  selector:
    matchLabels:
      app: bank-customer-management
  replicas: 1
  template:
    metadata:
      labels:
        app: bank-customer-management
    spec:
      containers:
      - name: bank-customer-management
        image: bank-customer-management
        imagePullPolicy: Never
        ports:
        - containerPort: 80