apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-transaction-processing-deployment
spec:
  selector:
    matchLabels:
      app: bank-transaction-processing
  replicas: 2
  template:
    metadata:
      labels:
        app: bank-transaction-processing
    spec:
      containers:
      - name: bank-transaction-processing
        image: bank-Ztransaction-processing
        imagePullPolicy: Never
        ports:
        - containerPort: 80